// souvenirItems.js - Data file for souvenir products
const souvenirItems = [
    {
        id: 1,
        name: "ASH-TREY NEW",
        price: 325,
        description: "Official Rimcollian ash tray with school emblem.",
        image: "/shop/ASH-TREY_NEW.png",
        stock: 15,
    },
    {
        id: 2,
        name: "ASH-TREY OLD",
        price: 110,
        description: "Classic design ash tray with Rimcollian emblem.",
        image: "/shop/ASH-TREY_OLD.png",
        stock: 20,
    },
    {
        id: 3,
        name: "BLEZER CREST",
        price: 500,
        description: "Embroidered blazer crest with Rimcollian emblem.",
        image: "/shop/BLEZER_CREST.png",
        stock: 25,
    },
    {
        id: 4,
        name: "BLUE SHORT",
        price: 420,
        description: "Official Rimcollian blue shorts for sports.",
        image: "/shop/BLUE_SHORT.png",
        stock: 30,
    },
    {
        id: 5,
        name: "BROCHURE",
        price: 10,
        description: "Rimcollian informational brochure.",
        image: "/shop/BROCHURE.png",
        stock: 100,
    },
    {
        id: 6,
        name: "BUTTON SET SILVER",
        price: 7000,
        description: "Premium silver button set with Rimcollian crest.",
        image: "/shop/BUTTON_SET_SILVER.png",
        stock: 5,
    },
    {
        id: 7,
        name: "BUTTON SET WHITE METAL",
        price: 770,
        description: "White metal button set featuring Rimcollian crest.",
        image: "/shop/BUTTON_SET_WHITE_METAL.png",
        stock: 15,
    },
    {
        id: 8,
        name: "CRAVET",
        price: 600,
        description: "Formal cravat with subtle Rimcollian pattern.",
        image: "/shop/CRAVET.png",
        stock: 18,
    },
    {
        id: 9,
        name: "CTL SET",
        price: 550,
        description: "Complete cufflinks and tie bar set.",
        image: "/shop/CTL_SET.png",
        stock: 12,
    },
    {
        id: 10,
        name: "GOLF CAP WITH CREST",
        price: 450,
        description: "Navy blue golf cap with embroidered Rimcollian crest.",
        image: "/shop/GOLF_CAP_WITH_CREST.png",
        stock: 20,
    },
    {
        id: 11,
        name: "HALF SLEEVE SHIRT WITH CREST",
        price: 825,
        description: "White half sleeve shirt with Rimcollian crest.",
        image: "/shop/HALF_SLEEVE_SHIRT_WITH_CREST.png",
        stock: 25,
    },
    {
        id: 12,
        name: "HALF SLEEVE SHIRT WITHOUT CREST",
        price: 795,
        description: "Plain white half sleeve shirt without crest.",
        image: "/shop/HALF_SLEEVE_SHIRT_WITHOUT_CREST.png",
        stock: 25,
    },
    {
        id: 13,
        name: "FIRST DAY COVER",
        price: 20,
        description: "Commemorative first day postal cover.",
        image: "/shop/FIRST_DAY_COVER.png",
        stock: 50,
    },
    {
        id: 14,
        name: "FIRST DAY COVER CANCELLED",
        price: 50,
        description: "Cancelled commemorative first day postal cover.",
        image: "/shop/FIRST_DAY_COVER_CANCELLED.png",
        stock: 30,
    },
    {
        id: 15,
        name: "LAPEL PIN SILVER",
        price: 800,
        description: "Silver lapel pin with Rimcollian crest.",
        image: "/shop/LAPEL_PIN_SILVER.png",
        stock: 10,
    },
    {
        id: 16,
        name: "LAPEL PIN WHITE METAL",
        price: 200,
        description: "White metal lapel pin with Rimcollian crest.",
        image: "/shop/LAPEL_PIN_WHITE_METAL.png",
        stock: 25,
    },
    {
        id: 17,
        name: "MEMENTO PLATE BIG",
        price: 1200,
        description: "Large commemorative plate with Rimcollian design.",
        image: "/shop/MEMENTO_PLATE_BIG.png",
        stock: 8,
    },
    {
        id: 18,
        name: "METAL CREST",
        price: 600,
        description: "Detailed metal Rimcollian crest for display.",
        image: "/shop/METAL_CREST.png",
        stock: 15,
    },
    {
        id: 19,
        name: "POCKET SQURE",
        price: 200,
        description: "Navy pocket square with Rimcollian design.",
        image: "/shop/POCKET_SQURE.png",
        stock: 30,
    },
    {
        id: 20,
        name: "RIMC CRESTED WHITE BEER MUG",
        price: 1500,
        description: "White ceramic beer mug with Rimcollian crest.",
        image: "/shop/RIMC_CRESTED_WHITE_BEER_MUG.png",
        stock: 12,
    },
    {
        id: 21,
        name: "RIMC HOODIE JACKET",
        price: 700,
        description: "Navy hoodie jacket with Rimcollian crest.",
        image: "/shop/RIMC_HOODIE_JACKET.png",
        stock: 18,
    },
    {
        id: 22,
        name: "RIMC FULL SLEEVE SHIRT",
        price: 550,
        description: "White full sleeve shirt with Rimcollian crest.",
        image: "/shop/RIMC_FULL_SLEEVE_SHIRT.png",
        stock: 22,
    },
    {
        id: 23,
        name: "RIMCOLLIAN MAROON TRACK SUIT",
        price: 1050,
        description: "Maroon track suit with Rimcollian branding.",
        image: "/shop/RIMCOLLIAN_MAROON_TRACK_SUIT.png",
        stock: 15,
    },
    {
        id: 24,
        name: "RIMC TRACK LOWER & UPPER",
        price: 1350,
        description: "Complete track suit with Rimcollian branding.",
        image: "/shop/RIMC_TRACK_LOWER_&_UPPER.png",
        stock: 14,
    },
    {
        id: 25,
        name: "RIMC T SHIRT",
        price: 500,
        description: "Navy blue t-shirt with Rimcollian crest.",
        image: "/shop/RIMC_T_SHIRT.png",
        stock: 35,
    },
    {
        id: 26,
        name: "ROLLER PEN WITH BOX",
        price: 320,
        description: "Quality roller pen with Rimcollian branding.",
        image: "/shop/ROLLER_PEN_WITH_BOX.png",
        stock: 20,
    },
    {
        id: 27,
        name: "SILVER SAREE BROOCH",
        price: 3400,
        description: "Elegant silver saree brooch with Rimcollian design.",
        image: "/shop/SILVER_SAREE_BROOCH.png",
        stock: 5,
    },
    {
        id: 28,
        name: "STAMP",
        price: 300,
        description: "Commemorative Rimcollian stamp collection.",
        image: "/shop/STAMP.png",
        stock: 25,
    },
    {
        id: 29,
        name: "TIE PIN",
        price: 200,
        description: "Elegant tie pin with Rimcollian crest.",
        image: "/shop/TIE_PIN.png",
        stock: 28,
    },
    {
        id: 30,
        name: "TIE RIMCOLLIAN",
        price: 400,
        description: "Navy tie with Rimcollian crest pattern.",
        image: "/shop/TIE_RIMCOLLIAN.png",
        stock: 30,
    },
    {
        id: 31,
        name: "T SHIRT VATS",
        price: 500,
        description: "Blue sports t-shirt with Rimcollian emblem.",
        image: "/shop/T_SHIRT_VATS.png",
        stock: 20,
    },
    {
        id: 32,
        name: "WHITE METAL SAREE BROOCH",
        price: 550,
        description: "White metal saree brooch with Rimcollian design.",
        image: "/shop/WHITE_METAL_SAREE_BROOCH.png",
        stock: 18,
    },
    {
        id: 33,
        name: "BOOK RIGALIA",
        price: 670,
        description: "Book about the heritage of Rimcollian tradition.",
        image: "/shop/BOOK_RIGALIA.png",
        stock: 15,
    },
    {
        id: 34,
        name: "BOOK PAVILION",
        price: 350,
        description: "Historical book about Rimcollian pavilion.",
        image: "/shop/BOOK_PAVILION.png",
        stock: 12,
    },
    {
        id: 35,
        name: "BOOK VEER KUMAR OF RAJWADA",
        price: 200,
        description: "Novel featuring Rimcollian characters.",
        image: "/shop/BOOK_VEER_KUMAR_OF_RAJWADA.png",
        stock: 10,
    },
    {
        id: 36,
        name: "BOOK SOARING PINES",
        price: 200,
        description: "Book about Rimcollian history and alumni.",
        image: "/shop/BOOK_SOARING_PINES.png",
        stock: 10,
    },
    {
        id: 37,
        name: "KEY CHAIN",
        price: 100,
        description: "Metal keychain with Rimcollian emblem.",
        image: "/shop/KEY_CHAIN.png",
        stock: 50,
    },
    {
        id: 38,
        name: "SECTION T SHIRT",
        price: 357,
        description: "Gray t-shirt with small Rimcollian emblem.",
        image: "/shop/SECTION_T_SHIRT.png",
        stock: 25,
    },
    {
        id: 39,
        name: "CD DOCUMENTRY",
        price: 199,
        description: "Documentary about Rimcollian history and achievements.",
        image: "/shop/CD_DOCUMENTRY.png",
        stock: 15,
    },
    {
        id: 40,
        name: "CALENDER",
        price: 350,
        description: "Rimcollian annual calendar with historical photos.",
        image: "/shop/CALENDER.png",
        stock: 20,
    }
];

export default souvenirItems;